dependencies:
  - { role: common/homebrew }
  - { role: common/python }
  - { role: common/ruby }
  - { role: common/nodejs }
  - { role: common/golang }
  - { role: common/nginx }
  - { role: common/dnsmasq }
